### ISSUE TITLE
can't run GO frontend

### ISSUE THREAD

**Issue by radumalica** [oxisto/titan#59]
``host OS Ubuntu 18.04
Docker-CE 18.06.1 version
``
pulled image from GIT, ran docker-compose and successfully started containers with redis and mongo 

Then i built the image for the actual app, with ``docker build -t titan:v0.1``, success.

While trying to issue docker run :
``
docker run -t eeafffcbebc2
psql: could not translate host name "titan" to address: Name does not resolve
pg_restore: too many command-line arguments (first is "sde-20190529-TRANQUILITY")
Try "pg_restore --help" for more information.
psql: could not translate host name "titan" to address: Name does not resolve
ERRO[0000] Could not read config: Config File "config" Not Found in "[/usr/titan/config]"
INFO[2019-07-03T11:25:12Z] Starting server...
ERRO[2019-07-03T11:25:12Z] Could not initialize EVE SSO, please specify a client ID, secret and redirect URI.
``

**Comment by oxisto** [comment]
Ok there are several things to this issue. First one is that I guess you used the `dev.yml` for docker compose and it looks like this one is completely outdated, since it still uses mongo, where as the newer version now uses postgres.

The second thing is that you need to specify the client ID, secret and redirect URI when running the container with docker run. This can either be done by specifiyng additional command line arguments or environment variables with `docker run -e ENV_VARIABLE`. I'll try to fix the `dev.yml` and adjust the README.md to include an example how to run it.

In the meantime, you need to register an application on https://developers.eveonline.com with the appropriate scopes and this will be your client ID and secret.
